import { useEffect, useState } from "react";
import { api, API_BASE, type Tender, type TenderAnalysis } from "./api";
import { supabase } from "./auth";

export default function App() {
  const [session,setSession]=useState<any>(null),[page,setPage]=useState("Dashboard"),[tenders,setTenders]=useState<Tender[]>([]);
  const [selected,setSelected]=useState<Tender|null>(null),[analysis,setAnalysis]=useState<TenderAnalysis|null>(null);
  const [contractor,setContractor]=useState<any>(null),[company,setCompany]=useState(""),[license,setLicense]=useState(""),[capacity,setCapacity]=useState(""),[experience,setExperience]=useState<any[]>([]),[equipment,setEquipment]=useState<any[]>([]),[expName,setExpName]=useState(""),[expType,setExpType]=useState(""),[expValue,setExpValue]=useState(""),[equipType,setEquipType]=useState(""),[equipQty,setEquipQty]=useState("1"),[matches,setMatches]=useState<any[]>([]),[matchTender,setMatchTender]=useState<Tender|null>(null);
  const [title,setTitle]=useState(""),[organization,setOrganization]=useState(""),[file,setFile]=useState<File|null>(null);
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[health,setHealth]=useState("Not checked");

  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
  const loadTenders=async()=>{if(session)try{setTenders(await api<Tender[]>("/tenders"))}catch{setTenders([])}}; useEffect(()=>{loadTenders()},[session]);
  const signIn=async()=>{setMessage("");const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)};
  const signUp=async()=>{setMessage("");const{error}=await supabase.auth.signUp({email,password});setMessage(error?error.message:"Account created. Check your email if confirmation is enabled.")};
  const signOut=async()=>{await supabase.auth.signOut();setPage("Dashboard")};
  const runMatch=async(t:Tender)=>{if(!contractor){await loadContractor()}let c=contractor;if(!c){setMessage("Create your contractor profile first.");setPage("Contractor Profile");return}setBusy(true);setMessage("");try{await api("/matches/"+t.id+"/"+c.id,{method:"POST"});const m=await api<any[]>("/matches/"+t.id);setMatches(m);setMatchTender(t);setPage("Matches")}catch(e){setMessage(e instanceof Error?e.message:"Unable to match tender.")}finally{setBusy(false)}};
  useEffect(()=>{if(session)loadContractor()},[session]);
  const loadContractor=async()=>{try{const list=await api<any[]>("/contractors/me");if(list[0]){const d=await api<any>("/contractors/"+list[0].id);setContractor(d.contractor);setCompany(d.contractor.company_name||"");setLicense(d.contractor.license_grade||"");setCapacity(String(d.contractor.financial_capacity??""));setExperience(d.experience||[]);setEquipment(d.equipment||[])}}catch{}};
  const addExperience=async()=>{if(!contractor)return setMessage("Save the contractor profile first.");if(!expName.trim())return setMessage("Enter project name.");try{await api("/contractors/"+contractor.id+"/experience",{method:"POST",body:JSON.stringify({project_name:expName,project_type:expType||null,contract_value:expValue?Number(expValue):null})});setExpName("");setExpType("");setExpValue("");setMessage("Experience added.");await loadContractor()}catch(e){setMessage(e instanceof Error?e.message:"Unable to add experience.")}};
  const addEquipment=async()=>{if(!contractor)return setMessage("Save the contractor profile first.");if(!equipType.trim())return setMessage("Enter equipment type.");try{await api("/contractors/"+contractor.id+"/equipment",{method:"POST",body:JSON.stringify({equipment_type:equipType,quantity:Number(equipQty)||1})});setEquipType("");setEquipQty("1");setMessage("Equipment added.");await loadContractor()}catch(e){setMessage(e instanceof Error?e.message:"Unable to add equipment.")}};
  const saveContractor=async()=>{if(!company.trim())return setMessage("Enter company name.");setBusy(true);setMessage("");try{if(contractor)throw new Error("Profile already exists. Editing will be added next.");const c=await api<any>("/contractors/me",{method:"POST",body:JSON.stringify({company_name:company,license_grade:license||null,financial_capacity:capacity?Number(capacity):null})});setContractor(c);setMessage("Contractor profile saved.");await loadContractor()}catch(e){setMessage(e instanceof Error?e.message:"Unable to save profile.")}finally{setBusy(false)}};
  const createTender=async()=>{if(!title.trim())return setMessage("Enter a tender title.");setBusy(true);try{const t=await api<Tender>("/tenders",{method:"POST",body:JSON.stringify({title,organization:organization||null})});if(file){const f=new FormData();f.append("file",file);await api("/tenders/"+t.id+"/documents/upload",{method:"POST",body:f})}setTitle("");setOrganization("");setFile(null);setMessage("Tender created successfully.");await loadTenders();setSelected(t);setPage("Tender Details")}catch(e){setMessage(e instanceof Error?e.message:"Unable to create tender.")}finally{setBusy(false)}};
  const openTender=(t:Tender)=>{setSelected(t);setAnalysis(null);setMessage("");setPage("Tender Details")};
  const runAnalysis=async()=>{if(!selected)return;setBusy(true);setMessage("");try{const r=await api<{tender_id:string,analysis:TenderAnalysis,requirements_created:number}>("/tenders/"+selected.id+"/analysis",{method:"POST"});setAnalysis(r.analysis);setSelected({...selected,status:"analyzed"});await loadTenders()}catch(e){setMessage(e instanceof Error?e.message:"Tender analysis failed.")}finally{setBusy(false)}};

  if(!session)return <div className="auth-page"><section className="auth-card"><h1>TenderIQ</h1><p className="muted">Tender intelligence for smarter bidding.</p><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary full" onClick={signIn}>Sign in</button><button className="secondary full" onClick={signUp}>Create account</button>{message&&<p>{message}</p>}<small>Configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in the frontend environment.</small></section></div>;

  const checkApi=async()=>{try{const r=await fetch(API_BASE+"/health");setHealth(r.ok?"API online":"API error")}catch{setHealth("API unreachable")}};
  return <div className="app"><aside><h1>TenderIQ</h1><p className="muted">Tender Intelligence Platform</p>{["Dashboard","Tenders","Contractor Profile","Matches"].map(x=><button className={page===x?"nav active":"nav"} onClick={()=>setPage(x)} key={x}>{x}</button>)}<div className="side-bottom"><button onClick={checkApi}>Check API</button><span>{health}</span><button onClick={signOut}>Sign out</button></div></aside>
  <main><header><div><p className="eyebrow">Tender Intelligence</p><h2>{page}</h2></div><button className="primary" onClick={()=>setPage("New Tender")}>+ New Tender</button></header>
  {page==="Dashboard"&&<Dashboard tenders={tenders} onOpen={openTender}/>}
  {page==="Tenders"&&<TenderList tenders={tenders} onNew={()=>setPage("New Tender")} onOpen={openTender}/>}
  {page==="New Tender"&&<section className="card form"><h3>Create tender</h3><input placeholder="Tender title *" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Organization" value={organization} onChange={e=>setOrganization(e.target.value)}/><label>Upload tender PDF<input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={busy} onClick={createTender}>{busy?"Creating...":"Create & Upload"}</button>{message&&<p>{message}</p>}</section>}
  {page==="Tender Details"&&selected&&<TenderDetails tender={selected} analysis={analysis} busy={busy} message={message} onAnalyze={runAnalysis} onBack={()=>setPage("Tenders")}/>}
  {page==="Contractor Profile"&&<ContractorProfile company={company} license={license} capacity={capacity} setCompany={setCompany} setLicense={setLicense} setCapacity={setCapacity} contractor={contractor} busy={busy} message={message} onSave={saveContractor} experience={experience} equipment={equipment} expName={expName} expType={expType} expValue={expValue} equipType={equipType} equipQty={equipQty} setExpName={setExpName} setExpType={setExpType} setExpValue={setExpValue} setEquipType={setEquipType} setEquipQty={setEquipQty} onAddExperience={addExperience} onAddEquipment={addEquipment}/>}
  {page==="Matches"&&<MatchPanel tender={matchTender} matches={matches} message={message} busy={busy} onOpenTender={openTender} />}</main></div>
}
function Dashboard({tenders,onOpen}:{tenders:Tender[],onOpen:(t:Tender)=>void}){return <><div className="hero"><div><h3>Know your tenders before you bid.</h3><p>Upload tender documents, extract requirements with AI, and compare them with your contractor profile.</p></div><button className="primary" onClick={()=>document.querySelector<HTMLButtonElement>(".nav:nth-of-type(2)")?.click()}>View Tenders</button></div><div className="grid">{[[""+tenders.filter(t=>t.status==="new").length,"New Tenders"],[""+tenders.filter(t=>t.status==="processing").length,"Processing"],[""+tenders.filter(t=>t.status==="analyzed").length,"Analyzed"],["0","Potential Matches"]].map(([n,l])=><div className="stat card" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><section className="card"><h3>Recent tenders</h3>{tenders.length?<TenderList tenders={tenders.slice(0,5)} onOpen={onOpen}/>:<p className="muted">No tenders yet. Create your first tender.</p>}</section></>}
function TenderList({tenders,onNew,onOpen}:{tenders:Tender[],onNew?:()=>void,onOpen:(t:Tender)=>void}){return <section className="card"><div className="row"><h3>Tenders</h3>{onNew&&<button className="primary" onClick={onNew}>+ New</button>}</div>{tenders.length?<div className="tender-list">{tenders.map(t=><button className="tender" key={t.id} onClick={()=>onOpen(t)}><div><strong>{t.title}</strong><span>{t.organization||"Organization not specified"}</span></div><b>{t.status}</b></button>)}</div>:<p className="muted">No tenders found.</p>}</section>}
function TenderDetails({tender,analysis,busy,message,onAnalyze,onBack}:{tender:Tender,analysis:TenderAnalysis|null,busy:boolean,message:string,onAnalyze:()=>void,onBack:()=>void}){const groups:[keyof TenderAnalysis,string][]=[["eligibility","Eligibility"],["required_documents","Required Documents"],["technical_requirements","Technical Requirements"],["financial_requirements","Financial Requirements"],["equipment_requirements","Equipment"],["personnel_requirements","Personnel"],["important_dates","Important Dates"],["risks_or_missing_information","Risks / Missing Information"]];return <section className="details"><button className="secondary" onClick={onBack}>← Back to tenders</button><div className="card detail-head"><div><p className="eyebrow">{tender.status}</p><h3>{tender.title}</h3><p className="muted">{tender.organization||"Organization not specified"}{tender.location?" · "+tender.location:""}</p></div><button className="primary" disabled={busy} onClick={onAnalyze}>{busy?"Analyzing...":"Analyze with AI"}</button></div>{message&&<div className="notice">{message}</div>}{analysis&&<><div className="card"><h3>AI Summary</h3><p>{analysis.summary||"No summary extracted."}</p><div className="meta-grid"><span><b>Type</b>{analysis.tender_type||"Not stated"}</span><span><b>Closing date</b>{analysis.closing_date||"Not stated"}</span><span><b>Location</b>{analysis.location||"Not stated"}</span></div></div><div className="analysis-grid">{groups.map(([key,label])=>{const value=analysis[key];return <div className="card" key={key}><h3>{label}</h3>{Array.isArray(value)&&value.length?<ul>{value.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="muted">Not found in document.</p>}</div>})}</div></>}</section>}

function ContractorProfile({company,license,capacity,setCompany,setLicense,setCapacity,contractor,busy,message,onSave,experience,equipment,expName,expType,expValue,equipType,equipQty,setExpName,setExpType,setExpValue,setEquipType,setEquipQty,onAddExperience,onAddEquipment}:{company:string,license:string,capacity:string,setCompany:(v:string)=>void,setLicense:(v:string)=>void,setCapacity:(v:string)=>void,contractor:any,busy:boolean,message:string,onSave:()=>void,experience:any[],equipment:any[],expName:string,expType:string,expValue:string,equipType:string,equipQty:string,setExpName:(v:string)=>void,setExpType:(v:string)=>void,setExpValue:(v:string)=>void,setEquipType:(v:string)=>void,setEquipQty:(v:string)=>void,onAddExperience:()=>void,onAddEquipment:()=>void}){return <section className="details"><div className="card form"><h3>Contractor Profile</h3><p className="muted">Build your company profile so TenderIQ can compare tender requirements against your capabilities.</p><input placeholder="Company name *" value={company} onChange={e=>setCompany(e.target.value)}/><input placeholder="License grade (e.g. GC-5)" value={license} onChange={e=>setLicense(e.target.value)}/><input type="number" placeholder="Financial capacity (ETB)" value={capacity} onChange={e=>setCapacity(e.target.value)}/><button className="primary" disabled={busy} onClick={onSave}>{busy?"Saving...":contractor?"Profile saved":"Save contractor profile"}</button>{message&&<p>{message}</p>}</div>{contractor&&<><div className="card form"><h3>Past Project Experience</h3><input placeholder="Project name *" value={expName} onChange={e=>setExpName(e.target.value)}/><input placeholder="Project type" value={expType} onChange={e=>setExpType(e.target.value)}/><input type="number" placeholder="Contract value (ETB)" value={expValue} onChange={e=>setExpValue(e.target.value)}/><button className="primary" onClick={onAddExperience}>+ Add Experience</button>{experience.map((x,i)=><div className="tender" key={i}><div><strong>{x.project_name}</strong><span>{x.project_type||"Project type not specified"}{x.contract_value?" · "+Number(x.contract_value).toLocaleString()+" ETB":""}</span></div></div>)}</div><div className="card form"><h3>Equipment</h3><input placeholder="Equipment type *" value={equipType} onChange={e=>setEquipType(e.target.value)}/><input type="number" min="1" placeholder="Quantity" value={equipQty} onChange={e=>setEquipQty(e.target.value)}/><button className="primary" onClick={onAddEquipment}>+ Add Equipment</button>{equipment.map((x,i)=><div className="tender" key={i}><div><strong>{x.equipment_type}</strong><span>Quantity: {x.quantity}</span></div></div>)}</div></>}</section>}

function MatchPanel({tender,matches,message,busy,onOpenTender}:{tender:Tender|null,matches:any[],message:string,busy:boolean,onOpenTender:(t:Tender)=>void}){const m=matches[0];return <section className="details"><div className="card"><div className="row"><div><p className="eyebrow">Requirement matching</p><h3>{tender?tender.title:"Select a tender"}</h3></div>{tender&&<button className="secondary" onClick={()=>onOpenTender(tender)}>View tender</button>}</div>{message&&<div className="notice">{message}</div>}{!m?<p className="muted">Open a tender and run matching after completing your contractor profile.</p>:<><div className="grid"><div className="stat card"><strong>{m.license_match===true?"✓":m.license_match===false?"✕":"?"}</strong><span>License</span></div><div className="stat card"><strong>{m.financial_match===true?"✓":m.financial_match===false?"✕":"?"}</strong><span>Financial</span></div><div className="stat card"><strong>{m.equipment_match===true?"✓":m.equipment_match===false?"✕":"?"}</strong><span>Equipment</span></div><div className="stat card"><strong>{m.experience_match===true?"✓":m.experience_match===false?"✕":"?"}</strong><span>Experience</span></div></div><div className="card"><h3>Requirement-by-requirement</h3>{m.match_details?.length?<div className="tender-list">{m.match_details.map((x:any,i:number)=><div className="tender" key={x.requirement_id||i}><div><strong>{x.type||"Requirement"} · {x.status.replace("_"," ")}</strong><span>{x.description}</span><span>{x.reason}</span>{x.evidence&&<span>Evidence: {x.evidence}</span>}</div></div>)}</div>:<p className="muted">No detailed results available yet.</p>}</div><div className="card"><h3>Items requiring attention</h3>{m.missing_requirements?.length?<ul>{m.missing_requirements.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul>:<p className="muted">No unresolved mandatory requirements recorded.</p>}<p className="muted">{m.notes}</p></div></>}</div></section>}
