import { useEffect, useState } from "react";
import { api, API_BASE, type Tender, type TenderAnalysis } from "./api";
import { supabase } from "./auth";

export default function App() {
  const [session,setSession]=useState<any>(null),[page,setPage]=useState("Dashboard"),[tenders,setTenders]=useState<Tender[]>([]);
  const [selected,setSelected]=useState<Tender|null>(null),[analysis,setAnalysis]=useState<TenderAnalysis|null>(null);
  const [title,setTitle]=useState(""),[organization,setOrganization]=useState(""),[file,setFile]=useState<File|null>(null);
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[health,setHealth]=useState("Not checked");

  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
  const loadTenders=async()=>{if(session)try{setTenders(await api<Tender[]>("/tenders"))}catch{setTenders([])}}; useEffect(()=>{loadTenders()},[session]);
  const signIn=async()=>{setMessage("");const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)};
  const signUp=async()=>{setMessage("");const{error}=await supabase.auth.signUp({email,password});setMessage(error?error.message:"Account created. Check your email if confirmation is enabled.")};
  const signOut=async()=>{await supabase.auth.signOut();setPage("Dashboard")};
  const createTender=async()=>{if(!title.trim())return setMessage("Enter a tender title.");setBusy(true);try{const t=await api<Tender>("/tenders",{method:"POST",body:JSON.stringify({title,organization:organization||null})});if(file){const f=new FormData();f.append("file",file);await api("/tenders/"+t.id+"/documents/upload",{method:"POST",body:f})}setTitle("");setOrganization("");setFile(null);setMessage("Tender created successfully.");await loadTenders();setSelected(t);setPage("Tender Details")}catch(e){setMessage(e instanceof Error?e.message:"Unable to create tender.")}finally{setBusy(false)}};
  const openTender=(t:Tender)=>{setSelected(t);setAnalysis(null);setMessage("");setPage("Tender Details")};
  const runAnalysis=async()=>{if(!selected)return;setBusy(true);setMessage("");try{const r=await api<{tender_id:string,analysis:TenderAnalysis,requirements_created:number}>("/tenders/"+selected.id+"/analysis",{method:"POST"});setAnalysis(r.analysis);setSelected({...selected,status:"analyzed"});await loadTenders()}catch(e){setMessage(e instanceof Error?e.message:"Tender analysis failed.")}finally{setBusy(false)}};

  if(!session)return <div className="auth-page"><section className="auth-card"><h1>TenderIQ</h1><p className="muted">Tender intelligence for smarter bidding.</p><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary full" onClick={signIn}>Sign in</button><button className="secondary full" onClick={signUp}>Create account</button>{message&&<p>{message}</p>}<small>Configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in the frontend environment.</small></section></div>;

  const checkApi=async()=>{try{const r=await fetch(API_BASE+"/health");setHealth(r.ok?"API online":"API error")}catch{setHealth("API unreachable")}};
  return <div className="app"><aside><h1>TenderIQ</h1><p className="muted">Tender Intelligence Platform</p>{["Dashboard","Tenders","Contractor Profile","Matches"].map(x=><button className={page===x?"nav active":"nav"} onClick={()=>setPage(x)} key={x}>{x}</button>)}<div className="side-bottom"><button onClick={checkApi}>Check API</button><span>{health}</span><button onClick={signOut}>Sign out</button></div></aside>
  <main><header><div><p className="eyebrow">Tender Intelligence</p><h2>{page}</h2></div><button className="primary" onClick={()=>setPage("New Tender")}>+ New Tender</button></header>
  {page==="Dashboard"&&<Dashboard tenders={tenders} onOpen={openTender}/>}
  {page==="Tenders"&&<TenderList tenders={tenders} onNew={()=>setPage("New Tender")} onOpen={openTender}/>}
  {page==="New Tender"&&<section className="card form"><h3>Create tender</h3><input placeholder="Tender title *" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Organization" value={organization} onChange={e=>setOrganization(e.target.value)}/><label>Upload tender PDF<input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={busy} onClick={createTender}>{busy?"Creating...":"Create & Upload"}</button>{message&&<p>{message}</p>}</section>}
  {page==="Tender Details"&&selected&&<TenderDetails tender={selected} analysis={analysis} busy={busy} message={message} onAnalyze={runAnalysis} onBack={()=>setPage("Tenders")}/>}
  {page==="Contractor Profile"&&<section className="card"><h3>Contractor Profile</h3><p className="muted">Company license, financial capacity, experience and equipment will be managed here.</p></section>}
  {page==="Matches"&&<section className="card"><h3>Tender Matches</h3><p className="muted">Requirement-by-requirement matching will appear here.</p></section>}</main></div>
}
function Dashboard({tenders,onOpen}:{tenders:Tender[],onOpen:(t:Tender)=>void}){return <><div className="hero"><div><h3>Know your tenders before you bid.</h3><p>Upload tender documents, extract requirements with AI, and compare them with your contractor profile.</p></div><button className="primary" onClick={()=>document.querySelector<HTMLButtonElement>(".nav:nth-of-type(2)")?.click()}>View Tenders</button></div><div className="grid">{[[""+tenders.filter(t=>t.status==="new").length,"New Tenders"],[""+tenders.filter(t=>t.status==="processing").length,"Processing"],[""+tenders.filter(t=>t.status==="analyzed").length,"Analyzed"],["0","Potential Matches"]].map(([n,l])=><div className="stat card" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><section className="card"><h3>Recent tenders</h3>{tenders.length?<TenderList tenders={tenders.slice(0,5)} onOpen={onOpen}/>:<p className="muted">No tenders yet. Create your first tender.</p>}</section></>}
function TenderList({tenders,onNew,onOpen}:{tenders:Tender[],onNew?:()=>void,onOpen:(t:Tender)=>void}){return <section className="card"><div className="row"><h3>Tenders</h3>{onNew&&<button className="primary" onClick={onNew}>+ New</button>}</div>{tenders.length?<div className="tender-list">{tenders.map(t=><button className="tender" key={t.id} onClick={()=>onOpen(t)}><div><strong>{t.title}</strong><span>{t.organization||"Organization not specified"}</span></div><b>{t.status}</b></button>)}</div>:<p className="muted">No tenders found.</p>}</section>}
function TenderDetails({tender,analysis,busy,message,onAnalyze,onBack}:{tender:Tender,analysis:TenderAnalysis|null,busy:boolean,message:string,onAnalyze:()=>void,onBack:()=>void}){const groups:[keyof TenderAnalysis,string][]=[["eligibility","Eligibility"],["required_documents","Required Documents"],["technical_requirements","Technical Requirements"],["financial_requirements","Financial Requirements"],["equipment_requirements","Equipment"],["personnel_requirements","Personnel"],["important_dates","Important Dates"],["risks_or_missing_information","Risks / Missing Information"]];return <section className="details"><button className="secondary" onClick={onBack}>← Back to tenders</button><div className="card detail-head"><div><p className="eyebrow">{tender.status}</p><h3>{tender.title}</h3><p className="muted">{tender.organization||"Organization not specified"}{tender.location?" · "+tender.location:""}</p></div><button className="primary" disabled={busy} onClick={onAnalyze}>{busy?"Analyzing...":"Analyze with AI"}</button></div>{message&&<div className="notice">{message}</div>}{analysis&&<><div className="card"><h3>AI Summary</h3><p>{analysis.summary||"No summary extracted."}</p><div className="meta-grid"><span><b>Type</b>{analysis.tender_type||"Not stated"}</span><span><b>Closing date</b>{analysis.closing_date||"Not stated"}</span><span><b>Location</b>{analysis.location||"Not stated"}</span></div></div><div className="analysis-grid">{groups.map(([key,label])=>{const value=analysis[key];return <div className="card" key={key}><h3>{label}</h3>{Array.isArray(value)&&value.length?<ul>{value.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="muted">Not found in document.</p>}</div>})}</div></>}</section>}
